# fly.toml app configuration file generated for styleup on 2024-11-12T22:46:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'styleup'
primary_region = 'gru'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
